brew "neovim"       # エディタ
brew "node"         # Node.js
brew "bat"          # catの改良版
brew "fd"           # findの改良版．telescope.nvimで必要
brew "tig"          # Gitクライアント
brew "tree"         # ディレクトリ構造を木形式で出力
brew "mas"          # Mac App Storeからインストールしたアプリを管理
brew "ghq"          # gitレポジトリ管理
brew "peco"         # フィルタツール (ghq連携のために導入)
brew "coreutils"    # GNU系基本コマンド
brew "findutils"    # GNU系ファイル検索コマンド
brew "gnu-sed"      # GNU系sedコマンド
brew "grep"         # GNU系grepコマンド

cask "raycast"                      # ランチャーアプリ
cask "google-chrome"                # ブラウザ
cask "docker"                       # Docker
cask "mactex-no-gui"                # LaTeX
cask "microsoft-office"             # Office
cask "obsidian"                     # メモ
cask "rectangle"                    # ウィンドウのスナップ
cask "slack"                        # Slack
cask "wezterm"                      # ターミナル
cask "font-plemol-jp"               # フォント
cask "intellij-idea-ce"             # IntelliJ Idea Community Edition
cask "visual-studio-code"           # Visual Studio Code
cask "postman"                      # APIテストツール
