return {
	-- -- 補完にアイコンを表示
	-- "onsails/lspkind-nvim",
	--
	-- -- LSPから補完をフェッチ
	-- "hrsh7th/cmp-nvim-lsp",
	--
	-- -- 関数入力時にその関数のシグネチャを表示
	-- "hrsh7th/cmp-nvim-lsp-signature-help",
	--
	-- -- LSPからドキュメントシンボルをフェッチ
	-- "hrsh7th/cmp-nvim-lsp-document-symbol",
	--
	-- -- Copilotから補完をフェッチ
	-- {
	-- 	"zbirenbaum/copilot-cmp",
	-- 	opt = {},
	-- },
	--
	-- -- バッファから補完をフェッチ
	-- "hrsh7th/cmp-buffer",
	--
	-- -- パスから補完をフェッチ
	-- "hrsh7th/cmp-path",
	--
	-- -- コマンドラインから補完をフェッチ
	-- "hrsh7th/cmp-cmdline",
	--
	-- -- スニペットから補完をフェッチ
	-- -- "saadparwaiz1/cmp_luasnip",
	--
	-- -- NeovimのLua APIから補完をフェッチ
	-- "hrsh7th/cmp-nvim-lua",
	--
	-- -- 計算から補完をフェッチ
	-- "hrsh7th/cmp-calc",
}
